import { Contact, Message, MessageStatus } from './types';

export const mockContacts: Contact[] = [
  {
    id: 'contact1',
    name: 'Pa Wandy',
    avatar: 'https://i.pravatar.cc/150?img=1',
    isOnline: true,
  },
  {
    id: 'contact2',
    name: 'Telkomsel',
    avatar: 'https://i.pravatar.cc/150?img=2',
    isOnline: false,
  },
  {
    id: 'contact3',
    name: '+62 812-4200-2471',
    avatar: 'https://i.pravatar.cc/150?img=3',
    isOnline: false,
  },
  {
    id: 'contact4',
    name: 'Meta AI',
    avatar: 'https://i.pravatar.cc/150?img=4',
    isOnline: true,
  },
  {
    id: 'contact5',
    name: '✨ Majelis Alloh ✨',
    avatar: 'https://i.pravatar.cc/150?img=5',
    isOnline: true,
  },
  {
    id: 'contact6',
    name: 'Gugie 913',
    avatar: 'https://i.pravatar.cc/150?img=6',
    isOnline: false,
  },
  {
    id: 'contact7',
    name: '+62 838-1455-0678',
    avatar: 'https://i.pravatar.cc/150?img=7',
    isOnline: false,
  },
  {
    id: 'contact8',
    name: 'Ruang Publik Nabiliyin',
    avatar: 'https://i.pravatar.cc/150?img=8',
    isOnline: true,
  },
];

export const mockMessages: Message[] = [
  {
    id: 'msg1',
    text: 'Bapak Deni dan Pak Wandy, selamat siang',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 2)),
    senderId: 'contact1',
    contactId: 'me',
    status: MessageStatus.READ,
  },
  {
    id: 'msg2',
    text: 'Siap',
    timestamp: new Date(new Date().setHours(new Date().getHours() - 1)),
    senderId: 'me',
    contactId: 'contact1',
    status: MessageStatus.READ,
  },
  {
    id: 'msg3',
    text: 'Wa alaikum salam wr wb',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 50)),
    senderId: 'me',
    contactId: 'contact3',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg4',
    text: 'baik terimakasih meta',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 45)),
    senderId: 'me',
    contactId: 'contact4',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg5',
    text: 'Aamin',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 30)),
    senderId: 'contact5',
    contactId: 'me',
    status: MessageStatus.READ,
  },
  {
    id: 'msg6',
    text: 'Owh iya ya',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 20)),
    senderId: 'me',
    contactId: 'contact6',
    status: MessageStatus.SENT,
  },
  {
    id: 'msg7',
    text: 'Assalamualaikum warohmatullohi wabai',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 10)),
    senderId: 'contact7',
    contactId: 'me',
    status: MessageStatus.READ,
  },
  {
    id: 'msg8',
    text: 'hehehe',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 5)),
    senderId: 'contact1',
    contactId: 'me',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg9',
    text: 'https://japrime.id/_cek/',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 4)),
    senderId: 'contact1',
    contactId: 'me',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg10',
    text: 'Okok aman',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 3)),
    senderId: 'contact1',
    contactId: 'me',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg11',
    text: 'Sementara ini aja dlu ku pakai',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 2)),
    senderId: 'contact1',
    contactId: 'me',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg12',
    text: 'Udah bangun?',
    timestamp: new Date(new Date().setMinutes(new Date().getMinutes() - 1)),
    senderId: 'contact1',
    contactId: 'me',
    status: MessageStatus.DELIVERED,
  },
  {
    id: 'msg13',
    text: 'Udah dr td pagi',
    timestamp: new Date(),
    senderId: 'me',
    contactId: 'contact1',
    status: MessageStatus.SENT,
  },
];